### ISSUE TITLE
Questions about the experiments

### ISSUE THREAD

**Issue by RaleighHan** [ylwangy/bert2vec#1]
Thanks for your nice work. I am reproducing your experiment using your released code.  However the training process is rather slow (thousands of hours),  could you please clarify the following numbers for me ? I would really appreciate it. 

1. the batch size of experiments (how many GPUs)
2. the estimated tuning time of one epoch 
3. how many epochs would the model reach to the converge.

**Comment by ylwangy** [comment]
Hi,

I remember that we just use the settings as in the word2vec.py file.
The training costs much time because we need to calculate the BERT representation for each words in each sentences, however, it should not be thousands of hours, as you said.
The results after training for 1~2 weeks should be good enough compared with other static word embeddings. (Due to the resource limitation, we only use 1 1080ti GPU for training. So you may optimize your training settings if you have more computation resources.)

Thanks!
